export class DatatableFakeData {
  public static rows = {
    indicator: [
      {
        responsive_id: '',
        id: 1,
        avatar: '',
        full_name: "Razón Corriente",
        post: 'a fin del trimestre actual o del trimestre de análisis',
        email: 'kocrevy0@thetimes.co.uk',
        city: '1.24',
        start_date: '09/23/2016',
        salary: 'Razón Corriente',
        age: '61',
        experience: '1 Year',
        status: 2
      },
      {
        responsive_id: 'Prueba Ácida',
        id: 2,
        avatar: '',
        full_name: 'Razones Financieras',
        post: 'a fin del trimestre actual o del trimestre de análisis',
        email: 'bcoulman1@yolasite.com',
        city: '1.19',
        start_date: '05/20/2018',
        salary: 'Prueba Ácida',
        age: '63',
        experience: '3 Years',
        status: 2
      },
      {
        responsive_id: '',
        id: 3,
        avatar: '',
        full_name: 'Período Promedio de Cobro',
        post: 'PPC(días)',
        email: 'sganderton2@tuttocitta.it',
        city: '34.88',
        start_date: '03/24/2018',
        salary: 'Período Promedio de Cobro',
        age: '66',
        experience: '6 Years',
        status: 5
      },
      {
        responsive_id: '',
        id: 4,
        avatar: '',
        full_name: 'Período Promedio de Pago',
        post: 'PPP(días)',
        email: 'bcoulman1@yolasite.com',
        city: 'error',
        start_date: '05/20/2018',
        salary: 'Período Promedio de Pago',
        age: '63',
        experience: '3 Years',
        status: 2
      },
      {
        responsive_id: '',
        id: 5,
        avatar: '',
        full_name: 'Rotación de Inventarios',
        post: '(veces)',
        email: 'sganderton2@tuttocitta.it',
        city: '4.40',
        start_date: '03/24/2018',
        salary: 'Rotación de Inventarios',
        age: '66',
        experience: '6 Years',
        status: 5
      },
      {
        responsive_id: '',
        id: 6,
        avatar: '',
        full_name: 'Período promedio de Inventarios',
        post: 'PPI(días)',
        email: 'bcoulman1@yolasite.com',
        city: '4.40',
        start_date: '05/20/2018',
        salary: 'Período promedio de Inventarios',
        age: '63',
        experience: '3 Years',
        status: 2
      },
      {
        responsive_id: '',
        id: 7,
        avatar: '',
        full_name: 'Prueba Ácida',
        post: '(veces)',
        email: 'sganderton2@tuttocitta.it',
        city: '4.40',
        start_date: '03/24/2018',
        salary: 'Rotación de Inventarios',
        age: '66',
        experience: '6 Years',
        status: 5
      },
      {
        responsive_id: '',
        id: 8,
        avatar: '',
        full_name: "Razón Corriente",
        post: '(veces)',
        email: 'kocrevy0@thetimes.co.uk',
        city: '4.40',
        start_date: '09/23/2016',
        salary: 'Rotación de Inventarios',
        age: '61',
        experience: '1 Year',
        status: 2
      },
      {
        responsive_id: 'Prueba Ácida',
        id: 9,
        avatar: '',
        full_name: 'Período promedio de cobro ',
        post: '(veces)',
        email: 'bcoulman1@yolasite.com',
        city: '4.40',
        start_date: '05/20/2018',
        salary: 'Rotación de Inventarios',
        age: '63',
        experience: '3 Years',
        status: 2
      },
      
    ],
    rubro: [
      {
        responsive_id: '',
        id: 1,
        avatar: '',
        full_name: "Activo Corriente",
        post: '',
        email: 'kocrevy0@thetimes.co.uk',
        city: 'Krasnosilka',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: '1 Year',
        status: 2
      },
      {
        responsive_id: '',
        id: 2,
        avatar: '',
        full_name: 'Cuentas por cobrar comerciales',
        post: '',
        email: 'bcoulman1@yolasite.com',
        city: 'Hinigaran',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: '3 Years',
        status: 2
      },
      {
        responsive_id: '',
        id: 3,
        avatar: '',
        full_name: 'Inventario de Mercaderías o existencias',
        post: '',
        email: 'sganderton2@tuttocitta.it',
        city: 'Golcowa',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: '6 Years',
        status: 5
      },
      {
        responsive_id: '',
        id: 4,
        avatar: '',
        full_name: 'Pasivo Corriente',
        post: '',
        email: 'sganderton2@tuttocitta.it',
        city: 'Golcowa',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: '6 Years',
        status: 5
      },
      {
        responsive_id: '',
        id: 5,
        avatar: '',
        full_name: 'Cuentas por cobrar comerciales',
        post: '',
        email: 'bcoulman1@yolasite.com',
        city: 'Hinigaran',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: '3 Years',
        status: 2
      },
      {
        responsive_id: '',
        id: 6,
        avatar: '',
        full_name: "Pasivo no Corriente",
        post: '',
        email: 'kocrevy0@thetimes.co.uk',
        city: 'Krasnosilka',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: '1 Year',
        status: 2
      },
      
      
      
      
    ],
    users: [
      {
        responsive_id: '',
        id: 1,
        avatar: 'avatar-s-10.jpg',
        full_name: "Alicia Estrada",
        post: '1',
        email: 'kocrevy0@thetimes.co.uk',
        city: 'Gratuito',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 2,
        avatar: 'avatar-s-1.jpg',
        full_name: 'Gian Carlos Pérez',
        post: '10',
        email: 'bcoulman1@yolasite.com',
        city: 'Gratuito',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 3,
        avatar: 'avatar-s-2.jpg',
        full_name: 'Juana Zuares Solis',
        post: '6',
        email: 'sganderton2@tuttocitta.it',
        city: 'Plan 2',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: 'El Bambino',
        status: 5
      },
      {
        responsive_id: '',
        id: 4,
        avatar: 'avatar-s-3.jpg',
        full_name: "Flor Anahi Linares Araya",
        post: '10',
        email: 'kocrevy0@thetimes.co.uk',
        city: 'Plan 2',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: 'Prueba Ácida',
        id: 5,
        avatar: 'avatar-s-5.jpg',
        full_name: 'Elvis Guillen',
        post: '1',
        email: 'bcoulman1@yolasite.com',
        city: 'Plan 2',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 6,
        avatar: 'avatar-s-6.jpg',
        full_name: 'Jhon Carlos Estrada', 
        post: '1',
        email: 'sganderton2@tuttocitta.it',
        city: 'Plan 2',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: 'El Bambino',
        status: 5
      },
      {
        responsive_id: '',
        id: 7,
        avatar: 'avatar-s-7.jpg',
        full_name: "Elena Perez",
        post: '1',
        email: 'kocrevy0@thetimes.co.uk',
        city: 'Plan 2',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      
    ],
    plantilla: [
      {
        responsive_id: '',
        id: 1,
        avatar: 'avatar-s-10.jpg',
        full_name: "Alicia Estrada",
        post: 'Plantilla 1',
        email: 'Plantilla1.docx',
        city: 'Gratuito',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 2,
        avatar: 'avatar-s-1.jpg',
        full_name: 'Gian Carlos Pérez',
        post: 'Plantilla 2',
        email: 'Plantilla2.docx',
        city: 'Gratuito',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 3,
        avatar: 'avatar-s-2.jpg',
        full_name: 'Juana Zuares Solis',
        post: 'Plantilla 3',
        email: 'Plantilla3.docx',
        city: 'Plan 2',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: 'El Bambino',
        status: 5
      },
      {
        responsive_id: '',
        id: 4,
        avatar: 'avatar-s-3.jpg',
        full_name: "Flor Anahi Linares Araya",
        post: 'Plantilla 4',
        email: 'Plantilla4.docx',
        city: 'Plan 2',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: 'Prueba Ácida',
        id: 5,
        avatar: 'avatar-s-5.jpg',
        full_name: 'Elvis Guillen',
        post: 'Plantilla 5',
        email: 'Plantilla5.docx',
        city: 'Plan 2',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 6,
        avatar: 'avatar-s-6.jpg',
        full_name: 'Jhon Carlos Estrada', 
        post: 'Plantilla 6',
        email: 'Plantilla6.docx',
        city: 'Plan 2',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: 'El Bambino',
        status: 5
      },
      {
        responsive_id: '',
        id: 7,
        avatar: 'avatar-s-7.jpg',
        full_name: "Elena Perez",
        post: 'Plantilla 7',
        email: 'Plantilla7.docx',
        city: 'Plan 2',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      
    ],
    table: [
      {
        responsive_id: '',
        id: 1,
        avatar: 'avatar-s-10.jpg',
        full_name: "Alicia Estrada",
        post: '1',
        email: 'Valor 1',
        city: 'Gratuito',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 2,
        avatar: 'avatar-s-1.jpg',
        full_name: 'Gian Carlos Pérez',
        post: '10',
        email: 'Valor 2',
        city: 'Gratuito',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 3,
        avatar: 'avatar-s-2.jpg',
        full_name: 'Juana Zuares Solis',
        post: '6',
        email: 'Valor 3',
        city: 'Plan 2',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: 'El Bambino',
        status: 5
      },
      
      
    ],
    plan: [
      {
        responsive_id: '',
        id: 1,
        avatar: 'avatar-s-10.jpg',
        full_name: "Plan 1",
        post: '1',
        email: 'S/ 5.00',
        city: 'SI',
        start_date: '09/23/2016',
        salary: 'I01',
        age: '61',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 2,
        avatar: 'avatar-s-1.jpg',
        full_name: 'Plan 2',
        post: '5',
        email: 'S/ 45.00',
        city: 'NO',
        start_date: '05/20/2018',
        salary: 'I01',
        age: '63',
        experience: 'El Bambino',
        status: 2
      },
      {
        responsive_id: '',
        id: 3,
        avatar: 'avatar-s-2.jpg',
        full_name: 'Plan 3',
        post: '10',
        email: 'S/ 80.00',
        city: 'NO',
        start_date: '03/24/2018',
        salary: 'I01',
        age: '66',
        experience: 'El Bambino',
        status: 5
      },
      
      
    ]
  };
}
